version: '3.3'

services:
  db:
    image: postgres:14.6
    volumes:
      - db_volue:/var/lib/postgresql/data/
    env_file:
      - ./.env
          
  backend:
    image: denchik79/foodgramm_backend:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_volue:/app/static/
      - media_volue:/app/media/
    env_file:
      - ./.env
  
  frontend:
    image: denchik79/foodgramm_frontend:latest
    volumes:
     - ../frontend:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volue:/var/html/static/
      - media_volue:/var/html/media/

volumes:
  db_volue:
  result_build:
  static_volue:
  media_volue: